export interface ParGolPartner {
  name: string;
  piva: string;
  sede: string;
  ateco: string;
  ula: string;
  agreementDate: string;
}

export interface ParGolCourse {
  slug: string;
  title: string;
  sep: string;
  eqf: string;
  education: string;
  duration: string;
  modality: string;
  cost: string;
  description: string;
  schedaUrl?: string;
  partner?: ParGolPartner;
}

export const PAR_GOL_COURSES: ParGolCourse[] = [
  {
    slug: 'configurare-un-sistema-di-archiviazione-gestione-e-verifica-dei-dati-personali-garantendone-la-sicurezza-e-la-riservatezza',
    title:
      'Configurare Un Sistema Di Archiviazione, Gestione E Verifica Dei Dati Personali, Garantendone La Sicurezza E La Riservatezza',
    sep: 'SEP 24 - Area Comune',
    eqf: '5',
    education: 'Diploma',
    duration: '120 ore',
    modality: 'Online',
    cost: 'Gratuito',
    description:
      "Il programma fornisce competenze teoriche e pratiche per creare e gestire sistemi sicuri per i dati personali, con particolare attenzione al rispetto della normativa GDPR. I contenuti principali includono: conformità normativa (applicazione del GDPR e leggi sulla protezione dati), progettazione sicura (implementazione di sistemi di archiviazione protetti in ogni fase), tecnologie di protezione (crittografia, backup sicuri, controllo accessi) e monitoraggio continuativo (identificazione di vulnerabilità e risposta agli incidenti). Il corso prepara professionisti a operare nel settore della gestione dati personali affrontando le sfide della sicurezza informatica e della regolamentazione.",
    partner: {
      name: 'Now S.r.l.s.',
      piva: '09618821210',
      sede: 'Via Corrado Alvaro, 8 – 80078 Pozzuoli',
      ateco: '63.11.19',
      ula: '0,67 al 12/2023',
      agreementDate: '27/06/2023',
    },
  },
  {
    slug: 'assistente-allautonomia-e-alla-comunicazione-delle-persone-con-disabilita-a-s-a-c-o-m',
    schedaUrl: 'https://capire.regione.campania.it/rrtq/public/scheda/575',
    title:
      "Assistente All'Autonomia E Alla Comunicazione Delle Persone Con Disabilità – (A.S.A.C.O.M.)",
    sep: 'SEP 19 - Servizi Socio-Sanitari',
    eqf: '4',
    education: 'Licenza Media + Qualificazione EQF 3',
    duration: '500 ore',
    modality: 'Online',
    cost: 'Gratuito',
    description:
      "La figura opera fornendo assistenza collegata alle attività socio-educative in favore di persone con disabilità di varia natura. Supporta la comunicazione tra persone con disabilità e insegnanti/educatori, preparando materiali didattici personalizzati. Nel contesto scolastico, collabora con l'insegnante di sostegno facilitando l'inclusione dell'alunno con disabilità secondo la Legge 104/92. Può operare come dipendente o autonomo presso strutture pubbliche e private che erogano servizi socio-educativi.",
    partner: {
      name: 'Smile Società Cooperativa Sociale-ONLUS',
      piva: '03172270617',
      sede: 'Via Tiziano Vecellio, 2 – 81030 Castel Volturno (CE)',
      ateco: '88.1',
      ula: '18 al 12/2023',
      agreementDate: '12/10/2023',
    },
  },
  {
    slug: 'gestione-magazzino-spedizioni-e-logistica',
    title: 'Gestione Magazzino Spedizioni e Logistica',
    sep: 'SEP 11 – Trasporti e Logistica',
    eqf: '3',
    education: 'Licenza Media',
    duration: '120 ore',
    modality: 'Online',
    cost: 'Gratuito',
    description:
      "Il programma formativo mira a sviluppare competenze nella gestione operativa degli spazi di stoccaggio e nella movimentazione sicura delle merci. I partecipanti apprendono tecniche per l'organizzazione ottimale degli spazi e la disposizione delle merci, al fine di velocizzare l'accesso e migliorare l'efficienza. Contenuti principali: organizzazione magazzino e gestione del personale, movimentazione interna sicura delle merci, software gestionali per tracciamento e controllo scorte, ottimizzazione dei flussi logistici e conformità normativa. Al completamento, i partecipanti possiedono conoscenze approfondite per gestire in modo efficace e sicuro le attività logistiche, garantendo una maggiore competitività aziendale.",
    partner: {
      name: 'Gespo S.r.l',
      piva: '07937731219',
      sede: 'Via dell\'Incoronata, 20/27 – 80133 Napoli (NA)',
      ateco: '81.21',
      ula: '14 al 03/2024',
      agreementDate: '26/06/2023',
    },
  },
  {
    slug: 'elaborazione-e-sviluppo-di-progetti-di-miglioramento-organizzativo',
    title: 'Elaborazione E Sviluppo Di Progetti Di Miglioramento Organizzativo',
    sep: 'SEP 24 - Area Comune',
    eqf: '5',
    education: 'Diploma',
    duration: '120 ore',
    modality: 'Online',
    cost: 'Gratuito',
    description:
      "Il programma fornisce strumenti e capacità per migliorare il funzionamento organizzativo, coprendo l'analisi dei processi aziendali, la progettazione di interventi mirati e l'applicazione di soluzioni che incrementino efficienza, efficacia e qualità complessiva. È rivolto a manager, responsabili del cambiamento e professionisti interessati a ottimizzare processi operativi, gestione risorse umane, strutture organizzative e risultati aziendali.",
    partner: {
      name: 'San Paolo 2.0 S.r.l.',
      piva: '09618801212',
      sede: 'Via Corrado Alvaro, 8 – 80078 Pozzuoli',
      ateco: '81.21',
      ula: '47,26 al 12/2023',
      agreementDate: '29/06/2023',
    },
  },
  {
    slug: 'competenze-digitali-di-base',
    title: 'Competenze Digitali di Base',
    sep: 'SEP 24 – Area Comune',
    eqf: '2',
    education: 'Licenza Elementare',
    duration: '60 ore',
    modality: 'Online',
    cost: 'Gratuito',
    description:
      "Il programma formativo è progettato per insegnare le conoscenze e le abilità fondamentali nell'uso consapevole delle tecnologie digitali. Rivolto a chi ha scarsa o nulla esperienza con dispositivi come computer, smartphone e tablet, il corso copre operazioni base come accensione dei dispositivi, navigazione web, utilizzo di applicazioni e software di produttività. Un elemento chiave è la sicurezza informatica: protezione dei dati personali e prevenzione di rischi come furti di identità e truffe online. L'obiettivo complessivo consiste nel permettere ai partecipanti di acquisire fiducia e competenza per affrontare il contesto digitale contemporaneo, indipendentemente dal livello iniziale di conoscenza.",
    partner: {
      name: 'Now S.r.l.s.',
      piva: '09618821210',
      sede: 'Via Corrado Alvaro, 8 – 80078 Pozzuoli',
      ateco: '63.11.19',
      ula: '0,67 al 12/2023',
      agreementDate: '27/06/2023',
    },
  },
  {
    slug: 'inglese-per-la-gestione-amministrativa',
    title: 'Inglese per la Gestione Amministrativa',
    sep: 'SEP 24 - Area Comune',
    eqf: '3',
    education: 'Licenza Media',
    duration: '120 ore',
    modality: 'Online',
    cost: 'Gratuito',
    description:
      "Il programma formativo approfondisce lo studio della lingua inglese applicata a contesti tecnico-amministrativi. L'obiettivo principale consiste nello sviluppare e potenziare le competenze linguistiche, al fine di migliorare la capacità di interagire efficacemente con una clientela internazionale. Durante il percorso, i partecipanti acquisiscono competenze per comprendere richieste clienti e fornire risposte pertinenti su ordini, fatture, spedizioni e aspetti amministrativi collegati ai servizi aziendali. Al termine, i corsisti sono in grado di gestire con sicurezza la comunicazione in inglese in un contesto professionale, rispondendo adeguatamente alle esigenze del mercato internazionale e contribuendo all'efficienza dei servizi aziendali.",
    partner: {
      name: 'San Paolo 2.0 S.r.l.',
      piva: '09618801212',
      sede: 'Via Corrado Alvaro, 8 – 80078 Pozzuoli',
      ateco: '63.11.19',
      ula: '47,26 al 12/2023',
      agreementDate: '28/06/2023',
    },
  },
  {
    slug: 'tecnico-commerciale-energie-rinnovabili',
    schedaUrl: 'https://capire.regione.campania.it/rrtq/public/scheda/253',
    title: 'Tecnico Commerciale Energie Rinnovabili',
    sep: 'SEP 12 - Servizi di distribuzione commerciale',
    eqf: '4',
    education: 'Licenza Media + Qualificazione EQF 3',
    duration: '300 ore',
    modality: 'Online',
    cost: 'Gratuito',
    description:
      "La figura rappresenta un tecnico-commerciale con specifica conoscenza del mercato e del territorio su cui opera. Si occupa dello sviluppo commerciale e della gestione delle relazioni clienti. Responsabilità principali: identificazione siti/clienti per progetti realizzativi e acquisizione autorizzazioni, analisi dati di vendita e andamenti di mercato, gestione ordini e assistenza clienti, servizi post-vendita e certificazione 9001:2008. Il trend di mercato registra un aumento del 30% delle richieste tra il 2009 e il 2010.",
    partner: {
      name: 'Now S.r.l.s.',
      piva: '09618821210',
      sede: 'Via Corrado Alvaro, 8 – 80078 Pozzuoli',
      ateco: '63.11.19',
      ula: '0,67 al 12/2023',
      agreementDate: '19/10/2022',
    },
  },
  {
    slug: 'addetto-al-servizio-ai-piani',
    schedaUrl: 'https://capire.regione.campania.it/rrtq/public/scheda/26',
    title: 'Addetto Al Servizio Ai Piani',
    sep: 'SEP 23 - Servizi Turistici',
    eqf: '2',
    education: 'Licenza Elementare',
    duration: '250 ore',
    modality: 'Online',
    cost: 'Gratuito',
    description:
      "La figura garantisce ordine e pulizia nelle camere e nelle aree comuni di strutture ricettive. Interagisce direttamente con i clienti alloggiati, assicurandosi della manutenzione delle stanze, della loro pulizia e del rifornimento della dotazione necessaria. Identifica eventuali guasti o malfunzionamenti e opera presso strutture turistico-ricettive, alberghiere ed extralberghiere, rispondendo al coordinatore del servizio ai piani e agli altri colleghi del team.",
    partner: {
      name: 'Gespo S.r.l',
      piva: '07937731219',
      sede: 'Via dell\'Incoronata, 20/27 – 80133 Napoli (NA)',
      ateco: '81.21',
      ula: '14 al 01/2024',
      agreementDate: '26/06/2023',
    },
  },
  {
    slug: 'oac-operatore-amministrativo-contabile',
    schedaUrl: 'https://capire.regione.campania.it/rrtq/public/scheda/712',
    title: 'OAC – Operatore Amministrativo Contabile',
    sep: 'SEP 24 – Area Comune',
    eqf: '5',
    education: 'Licenza Media',
    duration: '300 ore',
    modality: '210 ore online + 90 ore laboratorio',
    cost: 'Gratuito',
    description:
      "L'operatore svolge attività di supporto nelle operazioni di registrazione delle scritture contabili e degli adempimenti fiscali, previdenziali ed amministrativi secondo le normative vigenti. Le mansioni includono: gestione autonoma della segreteria, gestione delle comunicazioni interne ed esterne (mail, telefono, fax), manutenzione di archivi e protocolli cartacei e digitali, utilizzo di strumenti di Office Automation e attrezzature d'ufficio. Può operare in uffici della Pubblica Amministrazione, aziende private, associazioni di categoria e studi professionali, con livelli di specializzazione variabili in base alla dimensione organizzativa.",
    partner: {
      name: 'Now S.r.l.s.',
      piva: '09618811211',
      sede: 'Via Corrado Alvaro, 8 – 80078 Pozzuoli',
      ateco: '63.11.19',
      ula: '24,10 al 12/2023',
      agreementDate: '5/10/2022',
    },
  },
  {
    slug: 'social-media-manager',
    title: 'Social Media Manager',
    sep: 'SEP 12 - Servizi di distribuzione commerciale',
    eqf: '5',
    education: 'Diploma',
    duration: '300 ore',
    modality: 'Online',
    cost: 'Gratuito',
    description:
      "La figura gestisce operativamente i profili aziendali sui social, interagendo con gli utenti attraverso le piattaforme social per far crescere la presenza online, migliorare la brand awareness e la reputation, creare engagement, generare leads e fidelizzare il pubblico. Analizza i dati tramite tools specializzati e può operare come dipendente in agenzie, uffici marketing aziendali o come freelancer consulente.",
    schedaUrl: 'https://capire.regione.campania.it/rrtq/public/scheda/663',
    partner: {
      name: 'Now S.r.l.s.',
      piva: '09618821210',
      sede: 'Via Corrado Alvaro, 8 – 80078 Pozzuoli',
      ateco: '63.11.19',
      ula: '0,67 al 12/2023',
      agreementDate: '19/10/2022',
    },
  },
  {
    slug: 'operatore-segretariale',
    schedaUrl: 'https://capire.regione.campania.it/rrtq/public/scheda/478',
    title: 'Operatore Segretariale',
    sep: 'SEP 24 - Area Comune',
    eqf: '3',
    education: 'Licenza Media',
    duration: '200 ore',
    modality: '140 ore di lezione online e 60 ore di laboratorio',
    cost: 'Gratuito',
    description:
      'L’operatore segretariale organizza e gestisce le attività amministrative in vari aspetti tecnici, organizzativi e tecnologici. Tra i principali compiti rientrano: gestione dei flussi comunicativi in entrata e uscita, coordinamento dell’agenda dei dirigenti, disbrigo di pratiche burocratiche, organizzazione di riunioni e trasferte, accoglienza e gestione della corrispondenza. Le responsabilità variano secondo le dimensioni dell’organizzazione e la presenza di altre figure amministrative.',
    partner: {
      name: 'Now S.r.l.s.',
      piva: '09618801212',
      sede: 'Via Corrado Alvaro, 8 – 80078 Pozzuoli',
      ateco: '63.11.19',
      ula: '47,26 al 12/2023',
      agreementDate: '19/10/2022',
    },
  },
  {
    slug: 'operatore-edile',
    title: 'Operatore Edile',
    sep: 'SEP 09 - Edilizia',
    eqf: '3',
    education: 'Licenza Media',
    duration: '180 ore',
    modality: '90 ore di lezione online e 90 ore di laboratorio',
    cost: 'Gratuito',
    description:
      "L'Operatore Edile interviene nella realizzazione di opere edili con autonomia limitata, sotto supervisione. Le mansioni principali includono costruzione, riparazione e consolidamento di murature. Gestisce inoltre tutte le operazioni di allestimento, manutenzione e disallestimento del cantiere, inclusa l'installazione di opere provvisionali e relative misure di sicurezza. Assiste il responsabile nell'esecuzione dei tracciamenti, basandosi su disegni tecnici e istruzioni ricevute.",
    partner: {
      name: 'Edilizia Volante S.r.l.',
      piva: '09464241216',
      sede: 'Via M. Cervantes de Saavedra, 55/F – 80100 Napoli',
      ateco: '41.2',
      ula: '1 al 12/2023',
      agreementDate: '26/10/2022',
    },
  },
  {
    slug: 'tecnico-di-coordinamento-del-cantiere',
    schedaUrl: 'https://capire.regione.campania.it/rrtq/public/scheda/62',
    title: 'Tecnico di Coordinamento del Cantiere',
    sep: 'SEP 09 - Edilizia',
    eqf: '3',
    education: 'Licenza Media + Qualificazione EQF 3',
    duration: '300 ore',
    modality: '210 ore online + 90 ore laboratorio',
    cost: 'Gratuito',
    description:
      'Questa figura coordina le maestranze di cantiere organizzando le attività quotidiane e i materiali da impiegare. Supervisiona l’avanzamento dei lavori e gestisce l’approvvigionamento dalla fase d’ordine fino alla consegna in cantiere. Interviene sia nella costruzione di edifici che in opere di ingegneria civile presso imprese edili di diverse dimensioni, prevalentemente con incarichi dipendenti. Lavora con notevole grado di autonomia coordinandosi con il direttore di cantiere, il responsabile della sicurezza e le squadre operative, mantenendo la responsabilità della propria squadra di lavoro.',
    partner: {
      name: 'Edilizia Volante S.r.l.',
      piva: '09464241216',
      sede: 'Via M. Cervantes de Saavedra, 55/F – 80100 Napoli',
      ateco: '41.2',
      ula: '1 al 12/2023',
      agreementDate: '26/10/2022',
    },
  },
  {
    slug: 'operatore-del-servizio-di-sala-cameriere',
    schedaUrl: 'https://capire.regione.campania.it/rrtq/public/scheda/16',
    title: 'Operatore del Servizio di Sala – Cameriere',
    sep: 'SEP 23 - Servizi Turistici',
    eqf: '3',
    education: 'Licenza Media',
    duration: '300 ore',
    modality: '210 ore online + 90 ore laboratorio',
    cost: 'Gratuito',
    description:
      'Questa figura professionale si occupa dell’allestimento dei tavoli secondo le modalità del locale, dell’accoglienza dei clienti e dell’illustrazione del menù. Annota le ordinazioni, comunica con la cucina e serve ai tavoli. Prepara i conti e gestisce gli incassi. Lavora presso strutture ristorative, turistico-ricettive e catering, come dipendente (anche stagionale) o tramite contratti a chiamata, sotto la direzione del Maître e dello Chef, assumendosi piena responsabilità del rapporto con la clientela.',
    partner: {
      name: 'Azienda Agricola "Km 0 Flegreo" di Colandrea Generoso',
      piva: '08010411216',
      sede: 'Via Cappella, 313 – 80070 Monte di Procida (NA)',
      ateco: '56.10.12',
      ula: '0 al 12/2023',
      agreementDate: '12/10/2022',
    },
  },
  {
    slug: 'tecnico-commerciale-delle-vendite',
    schedaUrl: 'https://capire.regione.campania.it/rrtq/public/scheda/242',
    title: 'Tecnico commerciale delle vendite',
    sep: 'SEP 12 - Servizi di distribuzione commerciale',
    eqf: '4',
    education: 'Licenza Media + Qualificazione EQF 3',
    duration: '300 ore',
    modality: 'Online',
    cost: 'Gratuito',
    description:
      'Il tecnico commerciale delle vendite gestisce l’intero ciclo di distribuzione commerciale, occupandosi di pianificazione, organizzazione e controllo delle operazioni di acquisto, immagazzinamento e commercializzazione di prodotti alimentari e non. Le principali responsabilità includono: ricerca e selezione fornitori, allestimento spazi espositivi, gestione amministrativa, coordinamento delle attività promozionali, pianificazione dei servizi cliente pre e post-acquisto, e supervisione dello smaltimento dei rifiuti. Può operare come autonomo o dipendente, coordinando tutte le risorse aziendali per raggiungere gli obiettivi prefissati.',
    partner: {
      name: 'Master Boat S.r.l.s.',
      piva: '11939270010',
      sede: 'Via Roma, 45 – 10043 Orbassano (TO)',
      ateco: '77.21.09',
      ula: '0 al 12/2023',
      agreementDate: '26/10/2022',
    },
  },
  {
    slug: 'operatore-dellinfanzia',
    schedaUrl: 'https://capire.regione.campania.it/rrtq/public/scheda/440',
    title: 'Operatore dell’Infanzia',
    sep: 'SEP 19 - Servizi Socio-Sanitari',
    eqf: '4',
    education: 'Licenza Media + Qualificazione EQF 3',
    duration: '300 ore',
    modality: '210 ore online e 90 ore di laboratorio',
    cost: 'Gratuito',
    description:
      'La figura è incaricata di accudimento ed animazione rivolta a bambini e famiglie in contesti residenziali, comunitari e ospedalieri. Svolge mansioni socio-educative territoriali, sostiene la genitorialità tramite interventi familiari e collabora alla realizzazione di iniziative culturali e ricreative per favorire la socializzazione e lo sviluppo delle potenzialità dei minori.',
    partner: {
      name: 'Scuola Pascoli S.r.l.',
      piva: '09618811211',
      sede: 'Via Corrado Alvaro, 8 – 80078 Pozzuoli',
      ateco: '63.11.19',
      ula: '24,10 al 12/2023',
      agreementDate: '5/10/2022',
    },
  },
  {
    slug: 'operatore-call-center-inbound',
    schedaUrl: 'https://capire.regione.campania.it/rrtq/public/scheda/474',
    title: 'Operatore Call Center Inbound',
    sep: 'SEP 12 - Servizi di distribuzione commerciale',
    eqf: '3',
    education: 'Licenza Media',
    duration: '250 ore',
    modality: '175 ore di lezione online e 75 ore di laboratorio',
    cost: 'Gratuito',
    description:
      'La figura si occupa di gestire le comunicazioni in arrivo presso strutture di call center, fornendo supporto ai clienti attraverso vari canali (telefonico ed email). Le principali responsabilità includono assistenza clienti, supporto tecnico, elaborazione ordini e gestione reclami. L’operatore registra le varie attività e formula proposte ai diversi problemi presentati, operando in ambiti quali customer care, servizi informativi e help-desk tecnico.',
    partner: {
      name: 'Now S.r.l.s.',
      piva: '09618821210',
      sede: 'Via Corrado Alvaro, 8 – 80078 Pozzuoli',
      ateco: '63.11.19',
      ula: '0,67 al 12/2023',
      agreementDate: '19/10/2022',
    },
  },
  {
    slug: 'tecnico-esperto-in-campagne-comunicativo-promozionali',
    schedaUrl: 'https://capire.regione.campania.it/rrtq/public/scheda/497',
    title: 'Tecnico Esperto in Campagne Comunicativo/ Promozionali',
    sep: 'SEP 24 - Area Comune',
    eqf: '5',
    education: 'Licenza Media + Qualificazione EQF 3',
    duration: '300 ore',
    modality: '210 ore online + 90 ore laboratorio',
    cost: 'Gratuito',
    description:
      'Questo professionista gestisce l’intero ciclo comunicativo aziendale, sia interno che esterno. Le responsabilità includono: analizzare i mercati e i canali promozionali disponibili, sviluppare strategie comunicative allineate agli obiettivi aziendali, creare piani comunicativi, organizzare e gestire campagne pubblicitarie rispetto al budget definito, monitorare e valutare i risultati ottenuti. Può operare presso agenzie specializzate in comunicazione oppure negli uffici marketing/comunicazione di qualsiasi tipo di azienda.',
    partner: {
      name: 'Now S.r.l.s.',
      piva: '09618821210',
      sede: 'Via Corrado Alvaro, 8 – 80078 Pozzuoli',
      ateco: '63.11.19',
      ula: '0,67 al 12/2023',
      agreementDate: '19/10/2022',
    },
  },
  {
    slug: 'operatore-alla-conduzione-di-gru-e-di-apparecchi-di-sollevamento',
    schedaUrl: 'https://capire.regione.campania.it/rrtq/public/scheda/67',
    title: 'Operatore alla Conduzione di Gru e di Apparecchi di Sollevamento',
    sep: 'SEP 09 - Edilizia',
    eqf: '3',
    education: 'Licenza Media',
    duration: '300 ore',
    modality: '210 ore di lezione online e 90 ore di laboratorio',
    cost: 'Gratuito',
    description:
      'L’operatore specializzato nel settore edile conduce macchine di sollevamento quali muletti, gru a torre, autogru, sollevatori telescopici e piattaforme aeree. Gestisce lo spostamento di carichi e si occupa della manutenzione ordinaria dei mezzi. Opera prevalentemente con contratto dipendente presso aziende edili, collaborando con i colleghi e coordinandosi con i responsabili della sicurezza in cantiere, assumendo piena responsabilità delle proprie mansioni.',
    partner: {
      name: 'Edilizia Volante S.r.l.',
      piva: '09464241216',
      sede: 'Via M. Cervantes de Saavedra, 55/F – 80100 Napoli',
      ateco: '41.2',
      ula: '1 al 12/2023',
      agreementDate: '26/10/2022',
    },
  },
  {
    slug: 'operatore-alla-conduzione-di-macchine-complesse',
    schedaUrl: 'https://capire.regione.campania.it/rrtq/public/scheda/64',
    title: 'Operatore alla Conduzione di Macchine Complesse',
    sep: 'SEP 09 - Edilizia',
    eqf: '3',
    education: 'Licenza Media + Qualificazione EQF 3',
    duration: '300 ore',
    modality: '210 ore online + 90 ore laboratorio',
    cost: 'Gratuito',
    description:
      'Questa figura professionale realizza perforazioni di vario diametro e gestisce la manutenzione ordinaria dei mezzi relativi. Svolge il lavoro prevalentemente in cantieri di ingegneria civile con contratto dipendente presso imprese edili medio-grandi, principalmente private. Opera in coordinamento con colleghi e responsabili della sicurezza, assumendosi la responsabilità delle proprie attività nel settore costruzioni.',
    partner: {
      name: 'Edilizia Volante S.r.l.',
      piva: '09464241216',
      sede: 'Via M. Cervantes de Saavedra, 55/F – 80100 Napoli',
      ateco: '41.2',
      ula: '1 al 12/2023',
      agreementDate: '26/10/2022',
    },
  },
  {
    slug: 'operatore-socio-assistenziale-o-s-a',
    schedaUrl: 'https://capire.regione.campania.it/rrtq/public/scheda/672',
    title: 'Operatore Socio – Assistenziale (O.S.A.)',
    sep: 'SEP 19 - Servizi Socio-Sanitari',
    eqf: '3',
    education: 'Licenza Media',
    duration: '300 ore',
    modality: '210 ore di lezione online + 90 ore di laboratorio',
    cost: 'Gratuito',
    description:
      'L’Operatore Socio-Assistenziale assiste persone non autosufficienti presso il domicilio o in strutture socio-assistenziali, occupandosi di bisogni materiali e affettivi (igiene, alimentazione, ambiente). Lavora con soggetti vulnerabili quali disabili, anziani, persone con disagio psichico e minori. Collabora con medici, infermieri, fisioterapisti, assistenti sociali e psicologi, operando come dipendente, autonomo o in forma cooperativa. L’obiettivo è favorire autonomia, autodeterminazione e migliorare la qualità della vita degli assistiti.',
    partner: {
      name: 'Smile Società Cooperativa Sociale-ONLUS',
      piva: '03172270617',
      sede: 'Via Tiziano Vecellio, 2 – 81030 Castel Volturno (CE)',
      ateco: '88.1',
      ula: '18 al 12/2023',
      agreementDate: '12/10/2022',
    },
  },
  {
    slug: 'analista-di-sistemi-informativi',
    schedaUrl: 'https://capire.regione.campania.it/rrtq/public/scheda/238',
    title: 'Analista di Sistemi Informativi',
    sep: 'SEP 14 – Servizi di informatica',
    eqf: '5',
    education: 'Licenza Media + Qualificazione EQF 3',
    duration: '300 ore',
    modality: 'Online',
    cost: 'Gratuito',
    description:
      'La figura professionale definisce le soluzioni informatiche più appropriate, anche d’intesa con altri specialisti ICT, e gestisce le principali fasi dello sviluppo: analisi, specifica, collaudo e messa in servizio. Questo corso rientra nei programmi PAR GOL (Politiche Attive per il Lavoro) ed è erogato da Easy Work in modalità completamente online, senza costi per i partecipanti.',
    partner: {
      name: 'San Paolo 2.0 S.r.l.',
      piva: '09618801212',
      sede: 'Via Corrado Alvaro, 8 – 80078 Pozzuoli',
      ateco: '63.11.19',
      ula: '47,26 al 12/2023',
      agreementDate: '19/10/2022',
    },
  },
  {
    slug: 'operatore-del-punto-vendita',
    schedaUrl: 'https://capire.regione.campania.it/rrtq/public/scheda/243',
    title: 'Operatore del Punto Vendita',
    sep: 'SEP 12 – Servizi di distribuzione commerciale',
    eqf: '3',
    education: 'Licenza Media',
    duration: '250 ore',
    modality: '175 ore di lezione online e 75 ore di laboratorio',
    cost: 'Gratuito',
    description:
      'La figura è in grado di assistere, informare ed orientare il cliente per persuaderlo all’acquisto del prodotto e di allestire gli spazi espositivi. Inoltre gestisce il controllo qualità e quantità delle merci, cura l’igiene degli spazi, prepara e confeziona i prodotti secondo le richieste dei clienti e gestisce reclami e richieste post-vendita.',
    partner: {
      name: 'Master Boat S.r.l.s.',
      piva: '11939270010',
      sede: 'Via Roma, 45 – 10043 Orbassano (TO)',
      ateco: '77.21.09',
      ula: '0 al 12/2023',
      agreementDate: '26/10/2022',
    },
  },
  {
    slug: 'operatore-del-servizio-bar',
    schedaUrl: 'https://capire.regione.campania.it/rrtq/public/scheda/14',
    title: 'Operatore del Servizio Bar',
    sep: 'SEP 23 - Servizi Turistici',
    eqf: '3',
    education: 'Licenza Media',
    duration: '300 ore',
    modality: '210 ore di lezione online e 90 ore di laboratorio',
    cost: 'Gratuito',
    description:
      'La figura del barista prepara bevande e semplici snack caldi e freddi, curandone l’aspetto estetico, e li serve al banco e potenzialmente ai tavoli. Gestisce l’allestimento degli ambienti, verifica la disponibilità dei prodotti in magazzino e contatta i fornitori. Rispetta le normative sulla sicurezza alimentare e opera presso strutture ristorative con contratto dipendente, potenzialmente stagionale. Collabora con chef e camerieri, gestendo direttamente il rapporto con i clienti e assumendosi la responsabilità delle proprie mansioni.',
    partner: {
      name: 'Azienda Agricola "Km 0 Flegreo" di Colandrea Generoso',
      piva: '08010411216',
      sede: 'Via Cappella, 313 – 80070 Monte di Procida (NA)',
      ateco: '56.10.12',
      ula: '0 al 12/2023',
      agreementDate: '12/10/2022',
    },
  },
  {
    slug: 'segretario-coordinatore-amministrativo',
    schedaUrl: 'https://capire.regione.campania.it/rrtq/public/scheda/713',
    title: 'Segretario – Coordinatore Amministrativo',
    sep: 'SEP 24 - Area Comune',
    eqf: '5',
    education: 'Diploma',
    duration: '300 ore',
    modality: '210 ore di lezione online e 90 ore di laboratorio',
    cost: 'Gratuito',
    description:
      'La figura funge da ponte tra la direzione e le aree amministrativo-contabili in enti pubblici o privati. Fornisce supporto amministrativo di alto livello, collaborando con la direzione nella gestione di risorse umane, affari legali, acquisti e logistica. Le principali mansioni includono: redazione di relazioni e verbali con delibere organizzative, collaborazione alla documentazione per l’acquisizione di servizi, supporto nella redazione di bilanci, gestione dei rapporti con enti esterni su questioni amministrative. Data la trasversalità del profilo, può operare in aziende pubbliche o private di qualsiasi settore, nonché in studi legali o di consulenza amministrativa-contabile.',
    partner: {
      name: 'Now S.r.l.s.',
      piva: '09618801212',
      sede: 'Via Corrado Alvaro, 8 – 80078 Pozzuoli',
      ateco: '63.11.19',
      ula: '47,26 al 12/2023',
      agreementDate: '19/10/2022',
    },
  },
];
